name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - 'sdk-v[0-9]+.[0-9]+.[0-9]+-*'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - master
      - 'sdk-v[0-9]+.[0-9]+.[0-9]+-*'


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set env
        run: |
          fingerprint=$RANDOM
          echo "FINGERPRINT=$fingerprint" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
          driver: docker-container

      - name: Docker build
        env:
          DOCKER_BUILDKIT: 1
        run: >
          docker build -t nginx-test-${{ github.sha }} -f Dockerfile .

      - run: docker images --all

      - name: Export worker image(s)
        run: |
          docker image save nginx-test-${{ github.sha }} | gzip > nginx-test-${{ github.sha }}.tar.gz

      - name: Upload image
        uses: actions/upload-artifact@v3
        with:
          name: nginx-test-${{ github.sha }}.tar.gz
          path: nginx-test-${{ github.sha }}.tar.gz

  release:
    runs-on: ubuntu-latest
    name: Draft Release
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build]
    outputs:
      release_url: ${{ steps.create-release.outputs.html_url }}
      asset_upload_url: ${{ steps.create-release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v3

      - name: Download Worker Image
        uses: actions/download-artifact@v3
        with:
          name: nginx-test-${{ github.sha }}.tar.gz
          path: .

      - name: Save released teeracle
        run: |
            echo ${{ github.ref_name }}
            docker image load --input nginx-test-${{ github.sha }}.tar.gz
            docker tag nginx-test-${{ github.sha }} mosonyi/nginx-test:${{ github.ref_name }}
            docker image save mosonyi/nginx-test:${{ github.ref_name }} | gzip > nginx-test-${{ github.ref_name }}.tar.gz
            docker images --all
  
      - name: Upload nginx image
        uses: actions/upload-artifact@v3
        with:
          name: nginx-test-${{ github.ref_name }}.tar.gz
          path: nginx-test-${{ github.ref_name }}.tar.gz
  
      - name: Release
        id: create-release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: |
            NULL
          draft: true
          files: |
            nginx-test-${{ github.ref_name }}.tar.gz

      - name: Delete images
        run: |
            if [[ "$(docker images -q mosonyi/nginx-test:${{ github.ref_name }} 2> /dev/null)" != "" ]]; then
                docker image rmi --force mosonyi/nginx-test:${{ github.ref_name }} 2>/dev/null
            fi
            if [[ "$(docker images -q nginx-test-${{ github.sha }} 2> /dev/null)" != "" ]]; then
                docker image rmi --force nginx-test-${{ github.sha }} 2>/dev/null
            fi
            docker images --all
  
