name: Password test

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Password (foobar)"
        default: ""

jobs:
    hello:
        runs-on: [self-hosted]

        steps:
        - name: Add masks
          run: |
            echo "Secret is $SECRET"
            echo "::add-mask::$SECRET"

        - name: Set env vars
          run: |
            echo "SECRET=$SECRET" >> "$GITHUB_ENV"

        - name: Echo Step
          run: |
            echo "Password input is ${{ github.event.inputs.name }}"
            echo "Secret is ${{ env.SECRET }}"

        - name: Test pass
          env:
            CERTIFICATE_BASE64: ${{ secrets.PRIVKEY_B64 }}
          run: |
            echo $CERTIFICATE_BASE64 > privkey.pem.base64
            base64 -i --decode privkey.pem.base64 > privkey.pem
            echo ${{ github.event.inputs.name }} > passfile.txt
            openssl rsa -in privkey.pem -passin file:passfile.txt -pubout -out privkey.pub