name: Password test

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Password (foobar)"
        default: ""

jobs:
    hello:
        runs-on: [self-hosted]

        steps:
        - name: Add masks
          run: |
            echo "::add-mask::$SECRET"
            echo "::add-mask::$PRIVKEY_B64"
  
        - name: Set env vars
          run: |
            echo "SECRET=$SECRET" >> "$GITHUB_ENV"
  
        - name: Import secrets
          uses: hashicorp/vault-action@v2
          id: secrets
          with:
            url: http://192.168.95:8200
            token: ${{ env.SECRET }}
            exportEnv: false
            secrets: |
              secret/github privkey.pem.base64 | PRIVKEY_B64 ;

        - name: Echo Step
          run: |
            echo "Password input is ${{ github.event.inputs.name }}"
            echo "Secret is ${{ env.SECRET }}"
            echo "Privkey is is ${{ env.PRIVKEY_B64 }}"

        - name: Test pass
          env:
            CERTIFICATE_BASE64: ${{ env.PRIVKEY_B64 }}
          run: |
            echo $CERTIFICATE_BASE64 > privkey.pem.base64
            base64 -i --decode privkey.pem.base64 > privkey.pem
            echo ${{ github.event.inputs.name }} > passfile.txt
            openssl rsa -in privkey.pem -passin file:passfile.txt -pubout -out privkey.pub