name: Password test

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Password (foobar)"
        default: ""

jobs:
    hello:
        runs-on: ubuntu-latest

        steps:
        - name: Hello Step
          run: echo "Password input is ${{ github.event.inputs.name }}"

        - name: Test pass
          run: |
            echo ${{ secrets.PRIVKEY_B64 }} > privkey.pem.base64
            base64 -i --decode privkey.pem.base64 > privkey.pem
            openssl rsa -in privkey.pem -passin pass:${{ github.event.inputs.name }} -pubout -out privkey.pub