name: Publish Docker image for new releases

on:
  release:
    types:
      - published

jobs:
  main:
    name: Push to Dockerhub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Echo envs
        run: |
            echo "github.ref_name: ${{ github.ref_name }}"
            echo "github.event.release.tag_name: ${{ github.event.release.tag_name }}"

      - name: Download nginx from release
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "mosonyi/releasetest"
          version: "tags/${{ github.event.release.tag_name }}"
          file: nginx-test-${{ github.event.release.tag_name }}.tar.gz
          target: "nginx-test.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}
  

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Load Worker & Push
        env:
          DOCKER_BUILDKIT: 1
        run: |
            docker image load --input nginx-test.tar.gz
            docker images --all
            docker push mosonyi/nginx-test::${{ github.event.release.tag_name }}
  
      - name: Delete images
        run: |
          if [[ "$(docker images -q mosonyi/nginx-test::${{ github.event.release.tag_name }} 2> /dev/null)" != "" ]]; then
              docker image rmi --force mosonyi/nginx-test::${{ github.event.release.tag_name }} }} 2>/dev/null
          fi
          docker images --all
